AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  abc-renderer

  Sample SAM Template for abc-renderer

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30
    Tracing: Active
  Api:
    TracingEnabled: true
Resources:
  ABCRendererFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Architectures:
      - x86_64
      Events:
        ABCRenderer:
          Type: Api
          Properties:
            Path: /render
            Method: get
    Metadata:
      DockerTag: nodejs20.x-v1
      DockerContext: ./abc-renderer
      Dockerfile: Dockerfile

  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0
  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Ref: ApplicationResourceGroup
      AutoConfigurationEnabled: 'true'
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  ABCRendererApi:
    Description: API Gateway endpoint URL for Prod stage for ABC Renderer function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/abcrenderer/"
  ABCRendererFunction:
    Description: ABCRenderer Lambda Function ARN
    Value: !GetAtt ABCRendererFunction.Arn
  ABCRendererFunctionIamRole:
    Description: Implicit IAM Role created for ABCRenderer function
    Value: !GetAtt ABCRendererFunctionRole.Arn
